# coding: utf-8

"""
    Task Manager API

    A simple FastAPI-based Task Manager with JWT authentication.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from fastapi import FastAPI

from openapi_server.apis.default_api import router as DefaultApiRouter

app = FastAPI(
    title="Task Manager API",
    description="A simple FastAPI-based Task Manager with JWT authentication.",
    version="1.0.0",
debug=True
)

app.include_router(DefaultApiRouter)
